apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-v1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gauravkb/py-flask-webapp:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
metadata:
  name: flask-app-svc-v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4000
    nodePort: 32000
  selector:
    app: flask-app
